config/routes.rb
Rails.application.routes.draw do
  resources :lodgings
  resources :rooms
  resources :guests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/lodging.rb
class Lodging < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]


  # GET /guests
  # GET /guests.json
  def index
    @a_room = ["one", "two", "three", "four"]
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :guest_id)
    end
end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :set_lodging, only: [:show, :edit, :update, :destroy]

  # GET /lodgings
  # GET /lodgings.json
  def index
    @lodgings = Lodging.all
  end

  # GET /lodgings/1
  # GET /lodgings/1.json
  def show
  end

  # GET /lodgings/new
  def new
    @lodging = Lodging.new
  end

  # GET /lodgings/1/edit
  def edit
  end

  # POST /lodgings
  # POST /lodgings.json
  def create
    @lodging = Lodging.new(lodging_params)

    respond_to do |format|
      if @lodging.save
        format.html { redirect_to @lodging, notice: 'Lodging was successfully created.' }
        format.json { render :show, status: :created, location: @lodging }
      else
        format.html { render :new }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lodgings/1
  # PATCH/PUT /lodgings/1.json
  def update
    respond_to do |format|
      if @lodging.update(lodging_params)
        format.html { redirect_to @lodging, notice: 'Lodging was successfully updated.' }
        format.json { render :show, status: :ok, location: @lodging }
      else
        format.html { render :edit }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lodgings/1
  # DELETE /lodgings/1.json
  def destroy
    @lodging.destroy
    respond_to do |format|
      format.html { redirect_to lodgings_url, notice: 'Lodging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lodging
      @lodging = Lodging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lodging_params
      params.require(:lodging).permit(:room_id, :guest_name)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.fetch(:room, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest, local: true) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :guest_name %>
  </div>

  <div class="field">
    <%= form.label :guest_id %>
    <%= form.number_field :guest_id, id: :guest_guest_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1> Lodgings </h1>



<div class="manor-grounds flex-row">

<div class="first-rooms-column flex-column">

<div class="a-rooms flex-column">

  <div class="banquet-hall orient-center">
    <div class="center-text"> BANQUET HALL </div>
  </div>

  <%= @a_room.each_index do |idx| %>

    <div id="<%= idx+1 %>" ondrop="drop_handler(event);" ondragover="dragover_handler(event);" class="room-rectangle orient-center">
      <div class="center-text"> A<%= idx+1 %> </div>
    </div>

  <% end %>

</div>


<div class="c-rooms c-set1 flex-row">
  <div class="room-square orient-center">
    <div class="center-text"> C5 </div>
  </div>

  <div class="room-square orient-center">
    <div class="center-text"> C6 </div>
  </div>
</div>


<div class="c-rooms c-set2 flex-row">
  <div class="room-square orient-center">
    <div class="center-text"> C6 </div>
  </div>

  <div id="C7" ondrop="drop_handler(event);" ondragover="dragover_handler(event);" class="room-square orient-center">
    <div class="center-text"> C7 </div>
  </div>
</div>

</div>

<div class="second-rooms-column flex-column">

<div class="e-set flex-column">
  <div class="flex-row">
    <div class="room-square e-room orient-center">
      <div class="center-text"> E1 </div>
    </div>

    <div class="room-square e-room orient-center">
      <div class="center-text">  </div>
    </div>
  </div>

  <div class="flex-row">
    <div class="room-square e-room orient-center">
      <div class="center-text"> E2 </div>
    </div>

    <div class="room-square e-room orient-center">
      <div class="center-text"> E3 </div>
    </div>
  </div>
</div>

<div class="c-rooms c-set3 flex-column">
  <div class="room-square orient-center">
    <div class="center-text"> C12 </div>
  </div>

  <div class="room-square orient-center">
    <div class="center-text"> C11 </div>
  </div>
</div>

</div>

<div class="third-rooms-column flex-column">

<div class="c-set3 flex-row">
  <div class="flex-column">
    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C16 </div>
    </div>

    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C15 </div>
    </div>
  </div>

  <div class="flex-column">
    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C18 </div>
    </div>

    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C17 </div>
    </div>
  </div>

  <div class="flex-column">
    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C20 </div>
    </div>

    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C19 </div>
    </div>
  </div>

  <div class="flex-column">
    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C21 </div>
    </div>

    <div class="room-square c-set3__room orient-center">
      <div class="center-text"> C22 </div>
    </div>
  </div>

</div>

<div class="picnic-circle"> </div>


<div class="l-set flex-row">

  <div class="flex-column">
    <div class="room-square orient-center">
      <div class="center-text"> L23 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L24 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L25 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L26 </div>
    </div>
  </div>

  <div class="flex-column">
    <div class="room-square orient-center">
      <div class="center-text"> L27 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L28 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L29 </div>
    </div>

    <div class="room-square orient-center">
      <div class="center-text"> L30 </div>
    </div>
  </div>

</div>

</div>

</div>


<div class="guest-list">

  <p id="notice"><%= notice %></p>

  <h1>Guests</h1>

  <div class="flex-column">

    <% @guests.each do |guest| %>

      <span id='<%= guest.name%>' draggable="true" ondragstart="dragstart_handler(event);"  class="guest-name">
        <%= guest.name %>
      </span>

    <% end %>

  </div>

  <br>

  <%= link_to 'New Guest', new_guest_path %>
</div>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @guest.guest_id %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/lodgings/_form.html.erb
<%= form_with(model: lodging, local: true) do |form| %>
  <% if lodging.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lodging.errors.count, "error") %> prohibited this lodging from being saved:</h2>

      <ul>
      <% lodging.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :lodging_room_id %>
  </div>

  <div class="field">
    <%= form.label :guest_name %>
    <%= form.text_field :guest_name, id: :lodging_guest_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lodgings/edit.html.erb
<h1>Editing Lodging</h1>

<%= render 'form', lodging: @lodging %>

<%= link_to 'Show', @lodging %> |
<%= link_to 'Back', lodgings_path %>

app/views/lodgings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lodgings</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Guest name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lodgings.each do |lodging| %>
      <tr>
        <td><%= lodging.room_id %></td>
        <td><%= lodging.guest_name %></td>
        <td><%= link_to 'Show', lodging %></td>
        <td><%= link_to 'Edit', edit_lodging_path(lodging) %></td>
        <td><%= link_to 'Destroy', lodging, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lodging', new_lodging_path %>

app/views/lodgings/new.html.erb
<h1>New Lodging</h1>

<%= render 'form', lodging: @lodging %>

<%= link_to 'Back', lodgings_path %>

app/views/lodgings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @lodging.room_id %>
</p>

<p>
  <strong>Guest name:</strong>
  <%= @lodging.guest_name %>
</p>

<%= link_to 'Edit', edit_lodging_path(@lodging) %> |
<%= link_to 'Back', lodgings_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>